### ISSUE TITLE
Requires 49 more dependencies (excluding bluebird, request-promise, and node-google-translate-skidz)

### ISSUE THREAD

**Issue by ghost** [teralove/translate-chat#1]
```
error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\X\Proxy\bin\node_modules\Translate-chat\node-google-translate-skidz\lib\translate.js:3:11)

```
-------

```
PS C:\X\Desktop\New folder> npm install node-google-translate-skidz --save
npm WARN saveError ENOENT: no such file or directory, open 'C:\X\Desktop\New folder\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\X\Desktop\New folder\package.json'
npm WARN New folder No description
npm WARN New folder No repository field.
npm WARN New folder No README data
npm WARN New folder No license field.

+ node-google-translate-skidz@1.1.2
added 51 packages in 0.929s
```

**Comment by Risenio** [comment]
Added all of 'em to Translate-chat\node-modules

changed index L#5 from
>     const translate  = require('./node-google-translate-skidz');
to
>     const translate  = require('node-google-translate-skidz');

Works just prefect.

```
14:39 [Global][deezballs] : theyre all the same
14:39 [Global][deezballs(translation)] : they're all the same
14:39 [Global][deezballs] : period
14:39 [Global][Hornéyumustârd] : kroeans are dizzy japanese has nutty face and chinese is nasty
14:39 [Global][Hornéyumustârd(translation)] : koreans are dizzy japanese has nutty face and chinese is nasty
14:44 [Global][Hornéyumustârd] : such a shame so many ppl are into buddism
14:44 [Global][Hornéyumustârd(translation)] : such a shame so many ppl are into buddhism
14:44 [Global][Hornéyumustârd] : buddism is a korean religion
14:44 [Global][Hornéyumustârd(translation)] : buddhism is a korean religion
```

**Comment by ghost** [comment]
Added all of 'em to Translate-chat\node-modules

changed index L#5 from
>     const translate  = require('./node-google-translate-skidz');
to
>     const translate  = require('node-google-translate-skidz');

Works just prefect.

```
14:39 [Global][???] : theyre all the same
14:39 [Global][???(translation)] : they're all the same
14:39 [Global][???] : period
14:39 [Global][???] : kroeans are dizzy japanese has nutty face and chinese is nasty
14:39 [Global][???(translation)] : koreans are dizzy japanese has nutty face and chinese is nasty
14:44 [Global][???] : such a shame so many ppl are into buddism
14:44 [Global][???(translation)] : such a shame so many ppl are into buddhism
14:44 [Global][???] : buddism is a korean religion
14:44 [Global][???(translation)] : buddhism is a korean religion
14:48 [Global][???] : CERCO GIOCATORI ITALIANI PER GILDA
14:48 [Global][???(translation)] : I LOOK FOR ITALIAN PLAYERS FOR GILDA
```

**Comment by teralove** [comment]
Thanks for posting issue and providing the solution. Updated!
