### ISSUE TITLE
error: Cannot find module 'lodash' ?????

### ISSUE THREAD

**Issue by Joewwww** [teralove/translate-chat#3]
[02:02:56 GMT-0700] ERROR tera-proxy-game: [dispatch] load: error initializing module "translate-chat-master"
error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\tera-proxy\bin\node_modules\translate-chat-master\dependencies\node-google-translate-skidz\lib\translate.js:3:11)

I even tried latest proxy released in 5.28, still same error for me.....

**Comment by teralove** [comment]
Caali's proxy comes with lodash and other modules needed for translate-chat. So you could use Caali's and everything will be fine.

If you are not using Caali's proxy or don't want to. A solution is to copy all the folders inside "translate-chat/dependencies" and paste them into "tera-proxy/node_modules" **(Note: it is _not_  "bin/node_modules")**

This will work for now until I find a better solution.

**Comment by ghost** [comment]
@teralove You may just rename dependencies into node_modules, and change [This line](https://github.com/teralove/translate-chat/blob/553ebc30a8da892fd629d2dfaa52e71863368a1b/index.js#L5) into`     const translate  = require('node-google-translate-skidz');` Then there will be no problem for any other proxy, I tested it, It's been done [here e.g.](https://github.com/TeraProxy/Inspector), just for people who not familiar with that, it's up to you, just saying.

**Comment by teralove** [comment]
Thank you. That works beautifully
